export function stripEvimedTrailingQuestions(text: string): string {
  // 1. Strip duplicate evidence/reference sections generated by EviMed
  //    These overlap with our ## 参考文献 section built from structured quote data
  const cleaned = text.replace(
    /^##\s*(?:循证文献依据|循证处方依据|循证随访依据|参考文献|循证证据|文献依据)[\s\S]*?(?=^##\s|\s*$)/gm,
    ""
  );

  // 2. Strip trailing "是否希望..." bullets
  const lines = cleaned.split("\n");
  let end = lines.length;
  while (end > 0) {
    const line = lines[end - 1].trim();
    if (line === "" || /^[-•*]\s*是否/.test(line) || /^是否/.test(line)) {
      end--;
    } else {
      break;
    }
  }
  return lines.slice(0, end).join("\n");
}
